- hosts: wordpress
  become: yes

  tasks:
    - name: Update package repository
      apt:
        update_cache: yes
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: make sure and enable apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Install MySQL and PHP
      apt:
        name:
          - mysql-server
          - php
          - php-mysql
        state: present

    - name: make sure and enable mysql
      service:
        name: mysql
        state: started
        enabled: true

    - name: Install Python MySQL dependencies
      apt:
        name: python3-pymysql
        state: present

    - name: Create MySQL admin user
      mysql_user:
        name: wpadmin
        password: admin123#
        priv: "*.*:ALL,GRANT"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create WordPress database
      mysql_db:
        name: wpdb
        state: present
        login_user: wpadmin
        login_password: admin123#

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/
        remote_src: yes

    - name: Copy wp-config-sample.php to wp-config.php
      command: cp /var/www/wordpress/wp-config-sample.php /var/www/wordpress/wp-config.php
      args:
        creates: /var/www/wordpress/wp-config.php

    - name: Configure wp-config.php
      lineinfile:
        path: /var/www/wordpress/wp-config.php
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: "DB_NAME", line: "define('DB_NAME', 'wpdb');" }
        - { regexp: "DB_USER", line: "define('DB_USER', 'wpadmin');" }
        - { regexp: "DB_PASSWORD", line: "define('DB_PASSWORD', 'admin123#');" }
        - { regexp: "DB_HOST", line: "define('DB_HOST', 'localhost');" }

    - name: Update Apache VirtualHost for WordPress
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: "DocumentRoot /var/www/html"
        replace: "DocumentRoot /var/www/wordpress"

    - name: Enable the new site configuration
      command: a2ensite 000-default.conf

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted

- hosts: blog
  become: yes

  tasks:
    - name: Update package repository
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Rmake sure and enable apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Install MySQL and PHP
      apt:
        name:
          - mysql-server
          - php
          - php-mysql
          - git
        state: present

    - name: make sure and enable mysql
      service:
        name: mysql
        state: started
        enabled: true

    - name: Install Python MySQL dependencies
      apt:
        name: python3-pymysql
        state: present

    - name: Create MySQL admin user
      mysql_user:
        name: cyber
        password: pass2023
        priv: "*.*:ALL,GRANT"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create WordPress database
      mysql_db:
        name: cyber23
        state: present
        login_user: cyber
        login_password: pass2023

    - name: Clone a repo with separate git directory
      ansible.builtin.git:
        repo: "https://github.com/teguhbayu/ukk_tkj_2.git"
        dest: /var/www/webvuln
        single_branch: yes
        version: main

    - name: Import DB
      shell: mysql cyber23 < /var/www/webvuln/db.sql

    - name: Update Apache VirtualHost for webvuln
      replace:
        path: /etc/apache2/sites-available/000-default.conf
        regexp: "DocumentRoot /var/www/html"
        replace: "DocumentRoot /var/www/webvuln"

    - name: Enable the new site configuration
      command: a2ensite 000-default.conf

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
